
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nguyenhuy
 */
public class AddFrame extends javax.swing.JFrame {

    DictionaryCommandline Adder = new DictionaryCommandline();
    /**
     * Creates new form AddFrame
     */
    public AddFrame() throws FileNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Target = new javax.swing.JTextField();
        Explain = new javax.swing.JTextField();
        AddNew = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Word");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Target.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Target.setText("Nhập từ mới");
        Target.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TargetMouseClicked(evt);
            }
        });
        getContentPane().add(Target, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 241, 69));

        Explain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Explain.setText("Nhập nghĩa");
        Explain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExplainMouseClicked(evt);
            }
        });
        Explain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExplainActionPerformed(evt);
            }
        });
        getContentPane().add(Explain, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 253, 69));

        AddNew.setBackground(new java.awt.Color(255, 255, 255));
        AddNew.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguyenhuy\\Downloads\\icons8-add-new-40.png")); // NOI18N
        AddNew.setToolTipText("Thêm từ");
        AddNew.setOpaque(false);
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });
        getContentPane().add(AddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 60, 40));

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguyenhuy\\Downloads\\icons8-exit-40.png")); // NOI18N
        ExitButton.setToolTipText("Thoát");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 50, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tiếng Anh");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tiếng Việt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        BackGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguyenhuy\\Downloads\\b1.jpg")); // NOI18N
        BackGround.setText("add");
        BackGround.setOpaque(true);
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TargetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TargetMouseClicked
        Target.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_TargetMouseClicked

    private void ExplainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExplainMouseClicked
        Explain.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ExplainMouseClicked

    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed
        if(!Target.getText().equals("") && !Explain.getText().equals("")){
            if (!Adder.dictionaryLookUp(Target.getText()).equals("")) {
                JOptionPane.showMessageDialog(null, "Từ này đã có trong từ điển");
            }
            else{
                Adder.insertSingleWordFromCommanline(Target.getText(), Explain.getText());
                JOptionPane.showMessageDialog(rootPane, "Bạn vừa thêm từ " + Target.getText());
            }       
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Yêu cầu nhập đủ cả từ và nghĩa");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ExplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExplainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExplainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNew;
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField Explain;
    private javax.swing.JTextField Target;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
